from __future__ import annotations

from abc import ABC, abstractmethod

import numpy as np

from core.models import LIGHT_SPEED_MPS, RadioObservation, RangeEstimate


class BaseLde(ABC):
    name: str

    @abstractmethod
    def estimate(self, observation: RadioObservation) -> RangeEstimate:
        raise NotImplementedError

    @staticmethod
    def _refine_tof(
        observation: RadioObservation,
        coarse_idx: int,
    ) -> float:
        """Sub-sample ToF refinement via continuous (interpolated) CIR.

        Maps the coarse discrete bin to the interpolated CIR and finds the
        local peak to achieve sub-bin time resolution.  The continuous CIR
        is generated by zero-padded IFFT, equivalent to ideal bandlimited
        (sinc) interpolation.

        Returns the refined ToF in seconds.
        """
        factor = len(observation.t_cont_s) // len(observation.t_discrete_s)
        if factor < 2:
            return float(observation.t_discrete_s[coarse_idx])

        cont_start = coarse_idx * factor
        # Search a window of ±factor samples around the coarse bin centre
        half_window = max(factor, 3)
        lo = max(0, cont_start - half_window)
        hi = min(len(observation.t_cont_s), cont_start + half_window + 1)
        if lo >= hi:
            return float(observation.t_discrete_s[coarse_idx])

        window = np.abs(observation.cir_observed_cont[lo:hi])
        peak_offset = int(np.argmax(window))

        # Quadratic interpolation around the peak for sub-grid resolution
        if 1 <= peak_offset < len(window) - 1:
            y_left = window[peak_offset - 1]
            y_peak = window[peak_offset]
            y_right = window[peak_offset + 1]
            denom = y_left - 2.0 * y_peak + y_right
            if abs(denom) > 1e-20:
                delta = 0.5 * (y_left - y_right) / denom
                # Clamp to [-0.5, 0.5] — stay within the bin
                delta = max(-0.5, min(0.5, delta))
                t_step = observation.t_cont_s[1] - observation.t_cont_s[0]
                return float(observation.t_cont_s[lo + peak_offset] + delta * t_step)

        return float(observation.t_cont_s[lo + peak_offset])

    @staticmethod
    def _noise_stats(envelope: np.ndarray, tail_frac: float = 0.3) -> tuple[float, float]:
        n = len(envelope)
        tail_start = int(n * (1.0 - tail_frac))
        if tail_start >= n:
            tail_start = n // 2
        tail = envelope[tail_start:]
        if len(tail) < 4:
            tail = envelope[n // 2 :]
        return float(np.mean(tail)), float(np.std(tail))
