{
  "include": [
    "../defaults.yaml",
    "../radio_profiles/default_radios.yaml",
    "../observation/snr.yaml",
    "../channels/quick_start_tdl_a.yaml",
    "../experiments/ranging/ranging.yaml"
  ],
  "output_dir": "outputs"
}
