{
  "include": [
    "../defaults.yaml",
    "../radio_profiles/default_radios.yaml",
    "../observation/snr.yaml",
    "../impairments/none.yaml",
    "../channels/simple_room_2d.yaml",
    "../experiments/ranging/ranging.yaml"
  ],
  "output_dir": "outputs/simple_room_2d"
}
